hierarchical_encoder_params = {
    "vocab_size": 50000,
    "embed_dim": 1280,
    "hidden_size": 1280 * 4,
    "num_heads": 20,
    "dropout": 0.1,
    "segment_size": 32,
    "global_token_id": 4,
    "layers_type": [
        "segment",
        "global",
        "segment",
        "global",
        "segment",
        "global",
        "segment",
        "global",
        "segment",
        "global",
        "segment",
        "global",
        "segment",
        "global",
        "segment",
        "global",
        "segment",
        "global",
        "segment",
        "global",
        "segment",
        "global",
        "segment",
        "global",
    ],
}

decoder_params = {
    "vocab_size": 50000,
    "embed_dim": 1280,
    "num_layers": 6,
    "num_heads": 20,
    "hidden_size": 1280 * 4,
    "dropout": 0.1,
}

vanilla_encoder_params = {
    "vocab_size": 60000,
    "embed_dim": 512,
    "hidden_size": 512 * 4,
    "num_heads": 8,
    "num_layers": 6,
    "max_context_size": 1024,
    "dropout": 0.1,
}
